@URL_BASE=http://localhost:5005/graphql

###
POST {{URL_BASE}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetBook {
    book {
      title
      author {
        name
      }
    }
}

###
POST {{URL_BASE}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetMetricHistory {
  metricHistory(from: "2025-01-01T00:00:00z", to: "2025-04-01T00:00:00z") {
    timestamp
    value
  }
}
